import * as cdk from 'aws-cdk-lib'
import * as ec2 from 'aws-cdk-lib/aws-ec2'
import * as rds from 'aws-cdk-lib/aws-rds'
import * as elasticache from 'aws-cdk-lib/aws-elasticache'
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager'
import { Construct } from 'constructs'

interface DataStackProps extends cdk.StackProps {
  vpc: ec2.Vpc
  dbSg: ec2.SecurityGroup
  redisSg: ec2.SecurityGroup
}

export class DataStack extends cdk.Stack {
  readonly db: rds.DatabaseInstance
  readonly redis: elasticache.CfnCacheCluster
  readonly djangoSecret: secretsmanager.Secret
  readonly dbSecret: secretsmanager.Secret
  readonly anthropicSecret: secretsmanager.Secret

  constructor(scope: Construct, id: string, props: DataStackProps) {
    super(scope, id, props)

    const { vpc, dbSg, redisSg } = props

    // ─── SECRETS ────────────────────────────────────────────────────────────
    // Django secret key — auto-generated, stored in Secrets Manager
    this.djangoSecret = new secretsmanager.Secret(this, 'DjangoSecretKey', {
      secretName: 'topognosis/django-secret-key',
      generateSecretString: {
        passwordLength: 50,
        excludePunctuation: true,
      },
    })

    // Database credentials — auto-generated by CDK, stored in Secrets Manager
    this.dbSecret = new secretsmanager.Secret(this, 'DbSecret', {
      secretName: 'topognosis/db-credentials',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ username: 'topognosis' }),
        generateStringKey: 'password',
        excludePunctuation: true,
      },
    })

    // Anthropic API key — set manually after first deploy via AWS console
    this.anthropicSecret = new secretsmanager.Secret(this, 'AnthropicApiKey', {
      secretName: 'topognosis/anthropic-api-key',
      secretStringValue: cdk.SecretValue.unsafePlainText('REPLACE_ME'),
    })

    // ─── RDS (PostgreSQL) ───────────────────────────────────────────────────
    this.db = new rds.DatabaseInstance(this, 'Database', {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_15,
      }),
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MICRO),
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PUBLIC },
      securityGroups: [dbSg],
      credentials: rds.Credentials.fromSecret(this.dbSecret),
      databaseName: 'topognosis',
      deletionProtection: false,
      backupRetention: cdk.Duration.days(0),
      storageEncrypted: true,
      publiclyAccessible: false,
    })

    // ─── ELASTICACHE (Redis) ─────────────────────────────────────────────────
    // Subnet group — tells ElastiCache which subnets it can live in
    const redisSubnetGroup = new elasticache.CfnSubnetGroup(this, 'RedisSubnetGroup', {
      description: 'Subnet group for Redis',
      subnetIds: vpc.publicSubnets.map((s) => s.subnetId),
    })

    this.redis = new elasticache.CfnCacheCluster(this, 'Redis', {
      cacheNodeType: 'cache.t3.micro',
      engine: 'redis',
      numCacheNodes: 1,
      cacheSubnetGroupName: redisSubnetGroup.ref,
      vpcSecurityGroupIds: [redisSg.securityGroupId],
    })
  }
}
