# Generated by Django 5.2.13 on 2026-04-07 23:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dead_end', 'Dead End'), ('merged', 'Merged')], default='active', max_length=10)),
                ('materialized_context', models.JSONField(default=list)),
                ('compressed_context', models.JSONField(default=list)),
                ('delta_events', models.JSONField(default=list)),
                ('git_hash', models.CharField(blank=True, max_length=40)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('tool', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='graphs.graph')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='nodes.node')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('message_user', 'User Message'), ('message_ai', 'AI Message'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result'), ('branch', 'Branch'), ('merge', 'Merge'), ('compress', 'Compression'), ('checkout', 'Checkout')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nodes.node')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
