# Generated by Django 5.2.13 on 2026-04-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
