# Generated by Django 5.2.13 on 2026-04-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='inherited_context_length',
            field=models.IntegerField(default=0),
        ),
    ]
