# Generated by Django 5.2.13 on 2026-04-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_node_inherited_context_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent_event_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='snapshot_hash',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='event',
            name='tool_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
    ]
