# Generated by Django 5.2.13 on 2026-04-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_event_linkedlist_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='branched_from_event_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
